# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 3.0.{build}

# branches to build
branches:
  only:
    - master

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2022

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\myproject

# fetch repository as zip archive
shallow_clone: true

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Release

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\v3-cache'

# enable patching of AssemblyInfo.* files
dotnet_csproj:
  patch: true
  file: '**\FluentSimulator.csproj'
  version: '{version}'

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

install:
  - cmd: dotnet restore --verbosity minimal

# Build
build_script:
  - cmd: dotnet build

# Pack with Symbols
after_build:
  - cmd: dotnet pack --configuration Release --no-build --include-symbols --include-source --output ./artifacts

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  off

test_script:
  - cmd: dotnet test --logger "trx;LogFileName=TestResults.xml"

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key:
      secure: XJgryIiE07Gp0fNnPJJb48rtca7UecB5kPvdMBC4Ylufto1G5JyLYVvOrzFupdqH

artifacts:
  - path: TestResults.xml
    name: Test Report
  - path: ./artifacts/*.nupkg
    name: NuGet Package
